### ISSUE TITLE
Log the speed

### ISSUE THREAD

**Issue by oxapentane** [tlm-solutions/stasi#20]
Send the GPS speed (and preferably GPS bearing) with every GPS point.

This will make some interpolation magic in https://github.com/tlm-solutions/lofi and https://github.com/tlm-solutions/chemo easier, especially when the third data stream (TETRA) drops.

Obligatory meme (translation in the alt-text):
![-Why it smells like amphetamines in new moscow busses? -Because our passengers really value punctuality and comfort. And speed.](https://user-images.githubusercontent.com/1297357/235381882-459835a8-d6c9-45b7-beb2-cbd092d386ce.png)

**Comment by TKFRvisionOfficial** [comment]
This feature exists since the first version of this app.
